# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gaussian kernel
#'
#' @param ksize Side length of the squared kernel.
#' @param sigma Standard deviation of Gaussian weighting function.
#' @return A squared matrix sum to 1.
#' @export
#'
kernel_gauss <- function(ksize, sigma) {
    .Call(`_ydfun_kernel_gauss`, ksize, sigma)
}

#' Focal mean with a given kernel
#'
#' @param x A matrix.
#' @param kernel A kernel which can be produced by [kernel_gauss]
#' @param globe Are data at globe scale? If `TRUE`, both vertical
#' borders will be padded.
#' @return A matrix of focal mean.
#' @export
focal_mean <- function(x, kernel, globe) {
    .Call(`_ydfun_focal_mean`, x, kernel, globe)
}

#' Focal statistics on spatial window
#'
#' @param x A matrix.
#' @param y The other matrix.
#' @param rescale Rescale or not before computation.
#' @param xmin,xmax,ymin,ymax Normalization parameters. If `NA`, are calculated
#'   from the ranges of `x` and `y`, respectively.
#' @param ksize Side length of the spatial windows.
#' @param globe Are data at the global scale? If `TRUE`, two vertical borders
#'   will be padded before computation.
#' @param stat Statistic to return. One of 'xmn', 'ymn', 'xsd', or 'ysd'.
#' @return A matirx.
#' @export
focal_stat_sw <- function(x, y, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, globe = FALSE, stat = "xmn") {
    .Call(`_ydfun_focal_stat_sw`, x, y, rescale, xmin, xmax, ymin, ymax, ksize, globe, stat)
}

#' Focal statistics on temporal window
#'
#' This function computes the GCSM at each cell treating the 3rd dimension
#' as a temporal window.
#' @inheritParams focal_stat_sw
#' @param xmin,xmax,ymin,ymax Normalization parameters. If `NA`, are calculated
#'   from the ranges of `xxx` and `yyy`, respectively.
#' @param xxx A 3-d array with the 3rd dimension representing time.
#' @param yyy The other 3-d array.
#' @return A matrix.
#' @export
focal_stat_tw <- function(xxx, yyy, rescale = FALSE, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, stat = "xmn") {
    .Call(`_ydfun_focal_stat_tw`, xxx, yyy, rescale, xmin, xmax, ymin, ymax, stat)
}

