# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Focal statistics on spatial window
#'
#' @param x A matrix.
#' @param y The other matrix.
#' @param fuzzy Fuzzify or not prior to calculation.
#' @param xmin Lower limit of \code{x}. Defaults to \code{min(x)}.
#' @param xmax Upper limit of \code{x}. Defaults to \code{max(x)}.
#' @param ymin Lower limit of \code{y}. Defaults to \code{min(y)}.
#' @param ymax Upper limit of \code{y}. Defaults to \code{max(y)}.
#' @param ksize Side length of the spatial window.
#' @param global Are data at global scale? If \code{TRUE}, both vertical
#' borders will be padded.
#' @param stat Statistic to return. One of \code{c('xmn', 'ymn', 'xsd', 'ysd')}.
#' @return A matirx of \code{stat}.
#' @export
focal_stat_2d <- function(x, y, fuzzy, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, ksize = 9, global = FALSE, stat = "xmn") {
    .Call('_ydfun_focal_stat_2d', PACKAGE = 'ydfun', x, y, fuzzy, xmin, xmax, ymin, ymax, ksize, global, stat)
}

#' Focal statistics on temporal window
#'
#' This function computes the GCSM at each cell treating the 3rd dimension
#' as a temporal window.
#' @inheritParams focal_stat_2d
#' @param x A 3d array. The 3rd one is time.
#' @param y The other array.
#' @return A matrix of \code{stat}.
#' @export
focal_stat_3d <- function(x, y, fuzzy, xmin = NA_real_, xmax = NA_real_, ymin = NA_real_, ymax = NA_real_, stat = "xmn") {
    .Call('_ydfun_focal_stat_3d', PACKAGE = 'ydfun', x, y, fuzzy, xmin, xmax, ymin, ymax, stat)
}

